[package]
name = "diffs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.1"
log = "0.4.14"
env_logger = "0.9.0"
rayon = "1.5.1"
seahash = "4.1.0"